<link rel="stylesheet" href="{{ asset('admin_assets/css/accordions.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/alerts.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/meanmenu.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/nalika-icons.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/tabs.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/owl.carousel.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/owl.theme.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/owl.transitions.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/animate.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/normalize.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/main.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/morrisjs/morris.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/scrollbar/jquery.mCustomScrollbar.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/metisMenu/metisMenu.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/metisMenu/metisMenu-vertical.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/calendar/fullcalendar.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/calendar/fullcalendar.print.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/code-editor/codemirror.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/color-picker/color-picker.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/code-editor/ambiance.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/c3/c3.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/editor/select2.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/editor/datetimepicker.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/editor/bootstrap-editable.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/chosen/bootstrap-chosen.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/editor/x-editor-style.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/data-table/bootstrap-table.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/data-table/bootstrap-editable.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/datapicker/colorpicker.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/datapicker/datepicker3.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/duallistbox/bootstrap-duallistbox.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/buttons.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/modals.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/cropper/cropper.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/form/all-type-forms.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/responsive.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/dropzone/dropzone.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/form/themesaller.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/ionRangeSlider/ion.rangeSlider.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/ionRangeSlider/ion.rangeSlider.skinFlat.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/notifications/notificationse.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/notifications/Lobibox.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/preloader/preloader-style.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/select2/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/summernote/summernote.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/summernote/fonts/summernote.eot') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/summernote/fonts/summernote.ttf') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/summernote/fonts/summernote.woff') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/touchspin/jquery.bootstrap-touchspin.min.css') }}">
<link rel="stylesheet" href="{{ asset('admin_assets/css/tree-viewer/tree-viewer.css') }}">